### ISSUE TITLE
While video is rendering - sometimes the camera throws an Exception. 

### ISSUE THREAD

**Issue by vjvk** [twilio/twilio-video-app-android#226]
Hey Kindly help us out from this. 
As I am getting below crashes on the camera, while video is rendering on the ongoing call.

`
**E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:456: Camera 1: Error clearing streaming request: Function not implemented (-38)**
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:799)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1138)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:737)
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:239)
		`

Sometimes, this kind of crashes also am getting. These things are happening because of camera

`**CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): checkPidStatus:2069: The camera device has been disconnected**
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:834)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1214)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:539)
        at androidx.camera.camera2.internal.SynchronizedCaptureSessionBaseImpl.close(SynchronizedCaptureSessionBaseImpl.java:435)
        at androidx.camera.camera2.internal.CaptureSession.release(CaptureSession.java:438)
        at androidx.camera.camera2.internal.Camera2CameraImpl.releaseSession(Camera2CameraImpl.java:483)
        at androidx.camera.camera2.internal.Camera2CameraImpl.resetCaptureSession(Camera2CameraImpl.java:1098)
        at androidx.camera.camera2.internal.Camera2CameraImpl.tryDetachUseCases(Camera2CameraImpl.java:797)
        at androidx.camera.camera2.internal.Camera2CameraImpl.lambda$detachUseCases$12$Camera2CameraImpl(Camera2CameraImpl.java:768)`

If camera has been working fine for 10mins, later its automatically redirects to Freeze state.
Under **Camera2Capturer** Class

` @Override
                public void onCameraFreezed(final String errorMessage) {
                    reportError(new Exception(Exception.CAMERA_FROZE, errorMessage));
                }
`

Please suggest me , how to resolve this.

**Comment by Alton09** [comment]
Hi @vjvk ! Thank you for reaching out regarding this issue. Can you please fill out the bug report template as best as you can? This will help our team troubleshoot the issue. Also, are you modifying the original project's source code? Or are you simply using the project as is? Thanks!
