### ISSUE TITLE
Camera2Capturer is not supported on this device

### ISSUE THREAD

**Issue by daksh-huma** [twilio/twilio-video-app-android#251]
**Describe the bug**
I'm getting this exception.

     Caused by: java.lang.IllegalStateException: Camera2Capturer is not supported on this device
        at com.twilio.video.Preconditions.checkState(Preconditions.java:447)
        at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:216)
        at com.twilio.video.Camera2Capturer.<init>(Camera2Capturer.java:202)

**To Reproduce**
1. Accept the call on Android device

**Expected behavior**
1. The call should be accepted and work as expected

**Android Device (please complete the following information):**
 - Device: Xiaomi Mi A2 https://www.gsmarena.com/xiaomi_mi_a2_(mi_6x)-9140.php
 - API Version: API 29

**Video Android SDK (please complete the following information):**
- Version: 7.0.6

**Additional context**
- Camera2 version: 1.1.0-beta02

**Comment by alejo740** [comment]
@daksh-huma please, could you confirm if this issue still happening to you with the latest version? Thanks!

**Comment by alejo740** [comment]
I'm going to close the ticket but feel free to reach out again on this ticket if there are more questions.
